[package]
name = "game_2d"
version = "0.1.0"
authors = ["mfrench <mfrench@indeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"